### ISSUE TITLE
Detect changes not applied

### ISSUE THREAD

**Issue by ErwanMAS** [HewlettPackard/python-ilorest-library-EOL#14]
Hi , 

When we use the REST API , somes changes are not applied because we need to trigger a reboot .

Can we read a property via the REST API to detect this need of reboot ?

**Comment by LumbaJack** [comment]
That information should be returned in the payload from iLO. Can you tell me a bit more on which properties requires a reboot.

**Comment by ErwanMAS** [comment]
when you change some bios/setting  via the api . the request is saved somewhere .

on the next reboot , the bios detect if some changes must be apply , if yes , the bios apply and reboot . ( you can see a specific message in this case ) .

I am using a hp dl 360 gen9

**Comment by LumbaJack** [comment]
So after asking around we don't currently have a way to know before hand if the property change will require a reboot. For BIOS you can always assume you will need to reboot since it is a provider to the API and needs to go through post to read back the settings. Currently when you change a property you will have to parse the response for the message id "iLO.x.x.SystemResetRequired" to know if the property will take affect after reboot.
![2016-10-03_1127](https://cloud.githubusercontent.com/assets/4975816/19045161/ff43d352-895c-11e6-8987-9c57a23e79b2.png)
